package org.example.pojo;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;

@NoArgsConstructor
@AllArgsConstructor
@ToString
public class SalGrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salgrade.grade
     *
     * @mbg.generated Tue May 25 11:16:30 CST 2021
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salgrade.losal
     *
     * @mbg.generated Tue May 25 11:16:30 CST 2021
     */
    private Integer losal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salgrade.hisal
     *
     * @mbg.generated Tue May 25 11:16:30 CST 2021
     */
    private Integer hisal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salgrade.grade
     *
     * @return the value of salgrade.grade
     *
     * @mbg.generated Tue May 25 11:16:30 CST 2021
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salgrade.grade
     *
     * @param grade the value for salgrade.grade
     *
     * @mbg.generated Tue May 25 11:16:30 CST 2021
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salgrade.losal
     *
     * @return the value of salgrade.losal
     *
     * @mbg.generated Tue May 25 11:16:30 CST 2021
     */
    public Integer getLosal() {
        return losal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salgrade.losal
     *
     * @param losal the value for salgrade.losal
     *
     * @mbg.generated Tue May 25 11:16:30 CST 2021
     */
    public void setLosal(Integer losal) {
        this.losal = losal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salgrade.hisal
     *
     * @return the value of salgrade.hisal
     *
     * @mbg.generated Tue May 25 11:16:30 CST 2021
     */
    public Integer getHisal() {
        return hisal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salgrade.hisal
     *
     * @param hisal the value for salgrade.hisal
     *
     * @mbg.generated Tue May 25 11:16:30 CST 2021
     */
    public void setHisal(Integer hisal) {
        this.hisal = hisal;
    }
}